### ISSUE TITLE
Spongeforge - error gamestoping 

### ISSUE THREAD

**Issue by comdarksider** [EverCraft/EverPlugins#1]
I use spongeforge-1.10.2-2202-5.1.0-BETA-2099

Link error code :  http://pastebin.com/ngRGGgGw

**Comment by rexbut** [comment]
Was the scoreboard (Sidebar) enabled?

**Comment by rexbut** [comment]
Thank you for letting me know about the problem.

New version : http://jenkins.evercraft.fr/job/stable-5/
